# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.5
maven_group=net.morceaudebois.apolloparrot
archives_base_name=apolloparrot

# Fabric API
fabric_version=0.159.0+26.2

# path can be obtained with this command: /usr/libexec/java_home -v 25
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-25.jdk/Contents/Home